<img src = 'https://lh3.googleusercontent.com/-Q-N5-uawiEs/Xc1J1leI9wI/AAAAAAAAkcE/x63Of_HMkTQIeD5KFs_gIFadSgvvIWSOACK8BGAsYHg/s0/2019-11-14.png'/>

1. It’s a Python-based scientific computing package targeted at two sets of audiences.
2. A replacement for NumPy to use the power of GPUs.
3. A deep learning research platform that provides maximum flexibility and speed.
4. PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing. 
5. It is primarily developed by Facebook's artificial intelligence research group. It is free and open-source software released under the Modified BSD license.


### History
Facebook operated both PyTorch and Convolutional Architecture for Fast Feature Embedding (Caffe2), but models defined by the two frameworks were mutually incompatible. The Open Neural Network Exchange (ONNX) project was created by Facebook and Microsoft in September 2017 for converting models between frameworks. Caffe2 was merged into PyTorch at the end of March 2018.

#### PyTorch vs. Tensorflow
|Parameters|PyTorch|Tensorflow|
|-----------|-------|----------|
|Model Definition|The model is defined in a subclass and offers easy to use package|The model is defined with many, and you need to understand the syntax|
|GPU Support|Yes|Yes|
|Graph Type|Dynamic|Static|
|Tools|No visualization tool|You can use Tensorboard visualization tool|
|Community|The community still growing|Large active communities|

### Getting Started Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.



In [6]:
import torch as t

In [8]:
t.__version__

'1.2.0+cpu'

In [22]:
a = t.tensor([[5,10],[20,60]])
a

tensor([[ 5, 10],
        [20, 60]])

In [28]:
t.abs(t.tensor([-1, -2, 3]))

tensor([1, 2, 3])

In [32]:
a = t.randn(4)
t.acos(a)

tensor([0.4812, 0.8388, 2.7008, 1.2695])

In [34]:
t.acos_(a)

tensor([1.0687, 0.5756,    nan,    nan])

In [40]:
a = t.randn(4)
t.add(a,20)

tensor([21.1561, 19.9266, 19.5992, 21.2438])

In [44]:
M = t.randn(3, 5)
batch1 = t.randn(10, 3, 4)
batch2 = t.randn(10, 4, 5)

In [46]:
t.addbmm(M, batch1, batch2)

tensor([[-12.8302,  -2.7281,  -8.6240,  -1.8244,  -5.5802],
        [  0.9690,  -7.3421, -16.0144,   6.2360,  10.1697],
        [  1.2799,  -6.8116,   4.4409,  -9.7353,  -7.3442]])

In [47]:
# construct a 5x3 matrix
a=t.empty(5,3)
a

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])

In [48]:
# Random no matrix
b=t.rand(5,3)
b

tensor([[9.7038e-01, 2.0289e-01, 8.6071e-01],
        [7.6729e-01, 3.2838e-01, 4.8190e-04],
        [7.4028e-02, 7.9947e-01, 6.2426e-01],
        [2.1822e-01, 6.0415e-01, 1.1802e-01],
        [2.0336e-01, 9.8735e-01, 1.5378e-01]])

In [49]:
c=t.randn(5,3)
c

tensor([[-0.3343,  1.4613,  0.3591],
        [-0.7465,  1.1979, -2.0927],
        [-0.0818,  0.4312,  1.2663],
        [ 0.6762,  0.8394, -0.7313],
        [-0.4028, -0.4528, -0.6683]])

In [50]:
d=t.random(5,3)   # random not work in pytorch

TypeError: 'module' object is not callable

In [5]:
t.rand(5,3)

tensor([[0.1356, 0.9481, 0.2069],
        [0.9800, 0.0709, 0.2593],
        [0.2580, 0.8148, 0.4766],
        [0.0269, 0.9110, 0.0294],
        [0.0174, 0.0119, 0.9145]])

In [51]:
t.__config__

<module 'torch.__config__' from 'c:\\users\\reddy\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\torch\\__config__.py'>

Construct a matrix filled zeros and of dtype long:


In [52]:
a=t.zeros(10)
a

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
b=t.zeros(5,3,dtype=t.long)
b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

#### Construct a tensor directly from data:

In [ ]:
a=t.tensor(10)
a

tensor(10)

In [ ]:
b=t.tensor([5.5,3])
b

tensor([5.5000, 3.0000])

In [ ]:
b=t.arange(10)
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user


## new_

In [ ]:
a=a.new_ones(5,3,dtype=t.double)      # new_* methods take in sizes
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
a=t.randn_like(a,dtype=t.complex128) # all data type work except "Complex"

RuntimeError: No function is registered for schema aten::empty.memory_format(int[] size, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, MemoryFormat? memory_format=None) -> Tensor on tensor type ComplexCPUTensorId; available functions are CPUTensorId, MkldnnCPUTensorId, SparseCPUTensorId, VariableTensorId

In [ ]:
a=t.randn_like(a,dtype=t.float)             # override dtype!
a                                           # result has the same size

tensor([[ 0.1393,  1.3637, -0.2345],
        [-0.2731,  1.3095, -0.2041],
        [-0.8161,  0.2120, -0.3693],
        [-0.8447, -0.4595, -0.1200],
        [-1.3854,  1.0672, -0.9550]])

In [ ]:
a.size()

torch.Size([5, 3])

**Note**

#### ``torch.Size`` is in fact a tuple, so it supports all tuple operations.



# Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [ ]:
a

tensor([[ 0.1393,  1.3637, -0.2345],
        [-0.2731,  1.3095, -0.2041],
        [-0.8161,  0.2120, -0.3693],
        [-0.8447, -0.4595, -0.1200],
        [-1.3854,  1.0672, -0.9550]])

In [ ]:
b=t.randn(5,3)
b

tensor([[-2.1208,  0.4725, -0.0646],
        [-0.2195,  0.8029, -0.2826],
        [ 0.9933, -1.0271,  0.4310],
        [ 0.1533,  0.5382,  0.0662],
        [-2.3688,  0.1336, -1.2632]])

In [ ]:
print(a+b)

tensor([[-1.9815,  1.8362, -0.2990],
        [-0.4926,  2.1124, -0.4867],
        [ 0.1772, -0.8151,  0.0617],
        [-0.6914,  0.0787, -0.0538],
        [-3.7542,  1.2008, -2.2182]])


In [ ]:
t.add(a,b)

tensor([[-1.9815,  1.8362, -0.2990],
        [-0.4926,  2.1124, -0.4867],
        [ 0.1772, -0.8151,  0.0617],
        [-0.6914,  0.0787, -0.0538],
        [-3.7542,  1.2008, -2.2182]])

### Addition: providing an output tensor as argument



In [ ]:
res = t.empty(5,3)
res        

tensor([[1.0286e-38, 1.0653e-38, 9.1837e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39]])

In [ ]:
t.add(a,b,out=res)
print(res)             # res value is changed

tensor([[-1.9815,  1.8362, -0.2990],
        [-0.4926,  2.1124, -0.4867],
        [ 0.1772, -0.8151,  0.0617],
        [-0.6914,  0.0787, -0.0538],
        [-3.7542,  1.2008, -2.2182]])


### Addition: in-place

In [ ]:
# add a to b
b.add_(a)
print(b)   # b is changed bcoz "add_" so (underscore)

tensor([[-1.7030,  4.5636, -0.7680],
        [-1.0387,  4.7315, -0.8949],
        [-1.4550, -0.3910, -0.6769],
        [-2.3808, -0.8402, -0.2938],
        [-6.5251,  3.3353, -4.1281]])


## Note

Any operation that mutates a tensor in-place is post-fixed with an ``_``. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

You can use standard NumPy-like indexing with all bells and whistles!



In [ ]:
print(b[:,1])  # all rows but only 1st column

tensor([ 4.5636,  4.7315, -0.3910, -0.8402,  3.3353])


Resizing: If you want to resize/reshape tensor, you can use torch.view:



In [ ]:
x=t.randn(4,4)
print(x)
print()             # space line

y=x.view(16)        #  "view" converted size of 2D array into 1D array or vector
print(y)
print()

z=x.view(-1,8)      # reshape into 2x8 matrix(2D)  [-1 automatic take row as mapping]
print(z)

tensor([[-0.2084, -0.5540,  1.3042,  0.6991],
        [-0.8944, -0.7268,  0.6353, -2.2542],
        [-0.6461, -0.2023, -1.0190,  0.1222],
        [-3.5691, -0.4503,  0.2931, -1.4487]])

tensor([-0.2084, -0.5540,  1.3042,  0.6991, -0.8944, -0.7268,  0.6353, -2.2542,
        -0.6461, -0.2023, -1.0190,  0.1222, -3.5691, -0.4503,  0.2931, -1.4487])

tensor([[-0.2084, -0.5540,  1.3042,  0.6991, -0.8944, -0.7268,  0.6353, -2.2542],
        [-0.6461, -0.2023, -1.0190,  0.1222, -3.5691, -0.4503,  0.2931, -1.4487]])


In [ ]:
a=x.view(2,-1)   # automatic take column size
a

tensor([[-0.2084, -0.5540,  1.3042,  0.6991, -0.8944, -0.7268,  0.6353, -2.2542],
        [-0.6461, -0.2023, -1.0190,  0.1222, -3.5691, -0.4503,  0.2931, -1.4487]])

In [ ]:
x.size() , y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

If you have a one element tensor, use .item() to get the value as a Python number



In [ ]:
x=t.randn(1)
print(x)
print(x.item())

tensor([0.3535])
0.3535447120666504


In [ ]:
y=t.randn([10])
print(x)
print(x.item())

tensor([0.3535])
0.3535447120666504


In [ ]:
x=t.randn(1,2)
print(x)
print(x.item())      # only one element converted

tensor([[ 1.0654, -0.8526]])


ValueError: only one element tensors can be converted to Python scalars

In [ ]:
x=t.randn([1,2])
print(x)
print(x.item())   # only one element converted

tensor([[ 0.7815, -0.1614]])


ValueError: only one element tensors can be converted to Python scalars

**Read later:**

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described here <http://pytorch.org/docs/torch>_.



# NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.



**Converting a Torch Tensor to a NumPy Array**

In [ ]:
a=t.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


**See how the numpy array changed in value.**

In [ ]:
a.add_(1)   # add_(value)    value must be tensor not numpy or other type
print(a)
print(b)    # a changes also make in numpy array b

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a=np.ones(5)
b=t.from_numpy(a)
print(a,b)
print()

np.add(a,1,out=a)  #out=a means changes add changed saved in a
print(a)
print(b)           # b(tensor) value is changed

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.



# CUDA Tensors


Tensors can be moved onto any device using the .to method.


In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if t.cuda.is_available():
    device=t.device("cuda")                # a CUDA device object
    y=t.ones_lilkes(x,device=device)       # directly create a tensor on GPU
    x=x.to(device)                         # or just use strings ``.to("cuda")``
    z=x+y                                  
    print(z)
    print(z.to("cpu",t.double))            # ``.to`` can also change dtype together!

In [ ]:
a=t.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
b=t.zeros(3,3)
a+b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
c=t.arange(9).reshape(3,3)
c

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
c+a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
c.size()

torch.Size([3, 3])

In [ ]:
c.shape

torch.Size([3, 3])

In [ ]:
c.itemsize()

AttributeError: ignored

In [ ]:
c.ndim

2

In [ ]:
c-a

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.],
        [ 5.,  6.,  7.]])

In [ ]:
a*c

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
c/a

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
c//a

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
c%a

RuntimeError: ignored

# Indexing


In [ ]:
c[0]

tensor([0, 1, 2])

In [ ]:
c[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
c[:1]

tensor([[0, 1, 2]])

In [ ]:
c[-1:5]

tensor([[6, 7, 8]])

In [ ]:
a!=c

tensor([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [ ]:
a==c

tensor([[False,  True, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
a<c

tensor([[False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [ ]:
a>c

tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
a=t.tensor(10)
a

tensor(10)

In [ ]:
b=t.tensor([[1,2,3],[4,5,6],[7,8,9]])
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
b.dtype

torch.int64

# Scalar

In [ ]:
a=t.tensor(12)
a

tensor(12)

In [ ]:
a.ndim

0

In [ ]:
a.shape

torch.Size([])

In [ ]:
a.data

tensor(12)

In [ ]:
a.shape

torch.Size([])

In [ ]:
a.dtype

torch.int64

In [ ]:
b=t.tensor((10,20,30))  # more than 1 value u given value as a tuple
b

tensor([10, 20, 30])

In [ ]:
c=t.tensor(((1,2,3),(4,5,6)))
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
c=t.tensor((((1,2,3),(4,5,6)))) # bracket increased but got 2D array
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
d=t.tensor([10,10.5,True])
d

tensor([10.0000, 10.5000,  1.0000])

In [ ]:
e=t.tensor(("hello"))
# e=t.tensor(["hi"])
e

TypeError: ignored

In [ ]:
a=t.tensor([[1,2],3])
a

TypeError: ignored

In [ ]:
a=t.tensor([10,20])
print(a.astype(float))

AttributeError: ignored

# vector or 1D tensor

In [ ]:
a=t.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a.data

tensor([1, 2, 3])

In [ ]:
b=t.tensor({1,2,3})
b

RuntimeError: ignored

# 2D tensor

In [ ]:
c=t.tensor([(1,2,3)])
c

tensor([[1, 2, 3]])

In [ ]:
c=t.tensor([(1,2,True),(4,5,6)])
print(c)
c.dtype
# same as t.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 1],
        [4, 5, 6]])


torch.int64

In [ ]:
c=t.tensor([(1,2,3.15),(4,5,6)])
print(c)
c.dtype
# same as t.tensor([[1,2,3],[4,5,6]])

tensor([[1.0000, 2.0000, 3.1500],
        [4.0000, 5.0000, 6.0000]])


torch.float32

In [ ]:
c=t.tensor([(1,2,3),(4,5,6)])
print(c)
print(c.size())
c.dtype
# same as t.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


torch.int64

In [ ]:
a=t.tensor([2+3j])   # torch not support complex n string
b=t.tensor(["hi",1,2])
print(a)
print(b)

RuntimeError: ignored

In [ ]:
a=t.tensor([[1,2],[3,4]],dtype=t.complex64)
a     # complex not working in tensor type

RuntimeError: ignored

In [ ]:
a=t.tensor([[1,2],[3,4]],dtype=t.long)
a     # complex not working in tensor type

tensor([[1, 2],
        [3, 4]])

In [ ]:
a=t.tensor([[1,2],[3,4]],dtype=t.bool)
a     # complex not working in tensor type

tensor([[True, True],
        [True, True]])

In [ ]:
b=t.arange(12).reshape(4,3)
b

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
c=t.tensor(((1,2),(3,4)))
c

tensor([[1, 2],
        [3, 4]])

In [ ]:
c.shape

torch.Size([2, 2])

In [ ]:
c.size()

torch.Size([2, 2])

# 3D Tensor

In [ ]:
a=t.tensor([[[1,2],[3,4]]])
a

tensor([[[1, 2],
         [3, 4]]])

In [ ]:
b=t.tensor([((1,2),(3,4))])
b

tensor([[[1, 2],
         [3, 4]]])

In [ ]:
c.size()

torch.Size([1, 2, 3])

In [ ]:
c=t.tensor([[(1,2,3),(4,5,6)]])
c

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
# tried for 3D but got 2D array
d=t.tensor((([[1,2],[3,4]])))
d

tensor([[1, 2],
        [3, 4]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

torch.Size([1, 2, 3])

# Transposition

In [ ]:
a=t.tensor([1,2,3])
t.transpose(a,0,0)  # not possible bcoz they have only one axis

tensor([1, 2, 3])

In [11]:
b=t.tensor([[1,2],[3,4],[5,6]])
print(b.transpose)
print(t.transpose(b,1,0),"\n")  # both axis not equal so no transpose
b.T

<built-in method transpose of Tensor object at 0x000002B655F9BA98>
tensor([[1, 3, 5],
        [2, 4, 6]]) 



tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
a=t.tensor([[1,2],[3,4]])
t.transpose(a,0,1)         # axis=0 replace with axis=1

tensor([[1, 3],
        [2, 4]])

In [ ]:
a=t.tensor([[1,2],[3,4]])
t.transpose(a,1,0)

tensor([[1, 3],
        [2, 4]])